package com.aiminion.aiservice.common.enums;

public enum FeatureType {
	TRANSLATE,
	TRANSCRIBE,
	SUMMARIZE,
	GENERATE_CONTENT_TEXT,
	GENERATE_CONTENT_IMAGE,
	GENERATE_CONTENT,
	GENERATE_CONTENT_IMAGE_V2,
	GENERATE_CONTENT_V2,
	VOICEOVER
}
